### ISSUE TITLE
Improve documentation regarding endnotes

### ISSUE THREAD

**Issue by elinw** [tklebel/jstor#43]
Thanks for this, I'm so happy to have easily extracted most of the xml data.  However I noticed that some of the articles have endnotes rather than footnotes and I was wondering if you would consider adding a function to read those.

**Comment by tklebel** [comment]
Could you point me to a specific file that contains endnotes? A link to the file on JSTOR would be enough, then I can take a look.

**Comment by elinw** [comment]
http://www.jstor.org/stable/43264001

Here's the summary from find_article():
 basename_id journal_doi  journal_jcode journal_pub_id article_doi article_pub_id article_jcode
1    43264001          NA abajafhocodela                                                43264001
      article_type                                                                         article_title
1 research-article How to Respond to a Subpoena for Records by a Grand Jury or the HUD Inspector General
  volume issue language pub_day pub_month pub_year first_page last_page
1      3     4      eng       1         7     1994          7        15

**Comment by tklebel** [comment]
For this particularly article, the endnotes are stored in the `ref-list`, which `find_references` extracts. From my experience, if there is information about citations contained in the xml-file, it can be retrieved either with `find_footnotes` or `find_references`. However, the documentation for this could probably be clearer.

Where would you expect hints on this behavior, so that you would find out about it on your own?

**Comment by elinw** [comment]
Oh I really thought I had checked and double checked but they were in my references file.  I guess that makes sense in that endnotes are generally more like references than footnotes are and I think I was assuming they would be in footnotes since they are notes. Still, it would be good to document (I would probably put it in both places).

**Comment by tklebel** [comment]
Thanks for your comments! If you find any other issues, feel free to open another issue or create a pull request.
